// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/disism/karma/ent/dirs"
	"github.com/disism/karma/ent/predicate"
	"github.com/disism/karma/ent/saves"
	"github.com/disism/karma/ent/users"
)

// DirsQuery is the builder for querying Dirs entities.
type DirsQuery struct {
	config
	ctx        *QueryContext
	order      []dirs.OrderOption
	inters     []Interceptor
	predicates []predicate.Dirs
	withOwner  *UsersQuery
	withSaves  *SavesQuery
	withSubdir *DirsQuery
	withPdir   *DirsQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DirsQuery builder.
func (dq *DirsQuery) Where(ps ...predicate.Dirs) *DirsQuery {
	dq.predicates = append(dq.predicates, ps...)
	return dq
}

// Limit the number of records to be returned by this query.
func (dq *DirsQuery) Limit(limit int) *DirsQuery {
	dq.ctx.Limit = &limit
	return dq
}

// Offset to start from.
func (dq *DirsQuery) Offset(offset int) *DirsQuery {
	dq.ctx.Offset = &offset
	return dq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dq *DirsQuery) Unique(unique bool) *DirsQuery {
	dq.ctx.Unique = &unique
	return dq
}

// Order specifies how the records should be ordered.
func (dq *DirsQuery) Order(o ...dirs.OrderOption) *DirsQuery {
	dq.order = append(dq.order, o...)
	return dq
}

// QueryOwner chains the current query on the "owner" edge.
func (dq *DirsQuery) QueryOwner() *UsersQuery {
	query := (&UsersClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dirs.Table, dirs.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dirs.OwnerTable, dirs.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySaves chains the current query on the "saves" edge.
func (dq *DirsQuery) QuerySaves() *SavesQuery {
	query := (&SavesClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dirs.Table, dirs.FieldID, selector),
			sqlgraph.To(saves.Table, saves.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, dirs.SavesTable, dirs.SavesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubdir chains the current query on the "subdir" edge.
func (dq *DirsQuery) QuerySubdir() *DirsQuery {
	query := (&DirsClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dirs.Table, dirs.FieldID, selector),
			sqlgraph.To(dirs.Table, dirs.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, dirs.SubdirTable, dirs.SubdirPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPdir chains the current query on the "pdir" edge.
func (dq *DirsQuery) QueryPdir() *DirsQuery {
	query := (&DirsClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dirs.Table, dirs.FieldID, selector),
			sqlgraph.To(dirs.Table, dirs.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, dirs.PdirTable, dirs.PdirPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Dirs entity from the query.
// Returns a *NotFoundError when no Dirs was found.
func (dq *DirsQuery) First(ctx context.Context) (*Dirs, error) {
	nodes, err := dq.Limit(1).All(setContextOp(ctx, dq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dirs.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dq *DirsQuery) FirstX(ctx context.Context) *Dirs {
	node, err := dq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Dirs ID from the query.
// Returns a *NotFoundError when no Dirs ID was found.
func (dq *DirsQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = dq.Limit(1).IDs(setContextOp(ctx, dq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dirs.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dq *DirsQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := dq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Dirs entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Dirs entity is found.
// Returns a *NotFoundError when no Dirs entities are found.
func (dq *DirsQuery) Only(ctx context.Context) (*Dirs, error) {
	nodes, err := dq.Limit(2).All(setContextOp(ctx, dq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dirs.Label}
	default:
		return nil, &NotSingularError{dirs.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dq *DirsQuery) OnlyX(ctx context.Context) *Dirs {
	node, err := dq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Dirs ID in the query.
// Returns a *NotSingularError when more than one Dirs ID is found.
// Returns a *NotFoundError when no entities are found.
func (dq *DirsQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = dq.Limit(2).IDs(setContextOp(ctx, dq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dirs.Label}
	default:
		err = &NotSingularError{dirs.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dq *DirsQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := dq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DirsSlice.
func (dq *DirsQuery) All(ctx context.Context) ([]*Dirs, error) {
	ctx = setContextOp(ctx, dq.ctx, "All")
	if err := dq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Dirs, *DirsQuery]()
	return withInterceptors[[]*Dirs](ctx, dq, qr, dq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dq *DirsQuery) AllX(ctx context.Context) []*Dirs {
	nodes, err := dq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Dirs IDs.
func (dq *DirsQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if dq.ctx.Unique == nil && dq.path != nil {
		dq.Unique(true)
	}
	ctx = setContextOp(ctx, dq.ctx, "IDs")
	if err = dq.Select(dirs.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dq *DirsQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := dq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dq *DirsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dq.ctx, "Count")
	if err := dq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dq, querierCount[*DirsQuery](), dq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dq *DirsQuery) CountX(ctx context.Context) int {
	count, err := dq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dq *DirsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dq.ctx, "Exist")
	switch _, err := dq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dq *DirsQuery) ExistX(ctx context.Context) bool {
	exist, err := dq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DirsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dq *DirsQuery) Clone() *DirsQuery {
	if dq == nil {
		return nil
	}
	return &DirsQuery{
		config:     dq.config,
		ctx:        dq.ctx.Clone(),
		order:      append([]dirs.OrderOption{}, dq.order...),
		inters:     append([]Interceptor{}, dq.inters...),
		predicates: append([]predicate.Dirs{}, dq.predicates...),
		withOwner:  dq.withOwner.Clone(),
		withSaves:  dq.withSaves.Clone(),
		withSubdir: dq.withSubdir.Clone(),
		withPdir:   dq.withPdir.Clone(),
		// clone intermediate query.
		sql:  dq.sql.Clone(),
		path: dq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DirsQuery) WithOwner(opts ...func(*UsersQuery)) *DirsQuery {
	query := (&UsersClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withOwner = query
	return dq
}

// WithSaves tells the query-builder to eager-load the nodes that are connected to
// the "saves" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DirsQuery) WithSaves(opts ...func(*SavesQuery)) *DirsQuery {
	query := (&SavesClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withSaves = query
	return dq
}

// WithSubdir tells the query-builder to eager-load the nodes that are connected to
// the "subdir" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DirsQuery) WithSubdir(opts ...func(*DirsQuery)) *DirsQuery {
	query := (&DirsClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withSubdir = query
	return dq
}

// WithPdir tells the query-builder to eager-load the nodes that are connected to
// the "pdir" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DirsQuery) WithPdir(opts ...func(*DirsQuery)) *DirsQuery {
	query := (&DirsClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withPdir = query
	return dq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Dirs.Query().
//		GroupBy(dirs.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dq *DirsQuery) GroupBy(field string, fields ...string) *DirsGroupBy {
	dq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DirsGroupBy{build: dq}
	grbuild.flds = &dq.ctx.Fields
	grbuild.label = dirs.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Dirs.Query().
//		Select(dirs.FieldCreateTime).
//		Scan(ctx, &v)
func (dq *DirsQuery) Select(fields ...string) *DirsSelect {
	dq.ctx.Fields = append(dq.ctx.Fields, fields...)
	sbuild := &DirsSelect{DirsQuery: dq}
	sbuild.label = dirs.Label
	sbuild.flds, sbuild.scan = &dq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DirsSelect configured with the given aggregations.
func (dq *DirsQuery) Aggregate(fns ...AggregateFunc) *DirsSelect {
	return dq.Select().Aggregate(fns...)
}

func (dq *DirsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dq); err != nil {
				return err
			}
		}
	}
	for _, f := range dq.ctx.Fields {
		if !dirs.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dq.path != nil {
		prev, err := dq.path(ctx)
		if err != nil {
			return err
		}
		dq.sql = prev
	}
	return nil
}

func (dq *DirsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Dirs, error) {
	var (
		nodes       = []*Dirs{}
		withFKs     = dq.withFKs
		_spec       = dq.querySpec()
		loadedTypes = [4]bool{
			dq.withOwner != nil,
			dq.withSaves != nil,
			dq.withSubdir != nil,
			dq.withPdir != nil,
		}
	)
	if dq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, dirs.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Dirs).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Dirs{config: dq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dq.withOwner; query != nil {
		if err := dq.loadOwner(ctx, query, nodes, nil,
			func(n *Dirs, e *Users) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := dq.withSaves; query != nil {
		if err := dq.loadSaves(ctx, query, nodes,
			func(n *Dirs) { n.Edges.Saves = []*Saves{} },
			func(n *Dirs, e *Saves) { n.Edges.Saves = append(n.Edges.Saves, e) }); err != nil {
			return nil, err
		}
	}
	if query := dq.withSubdir; query != nil {
		if err := dq.loadSubdir(ctx, query, nodes,
			func(n *Dirs) { n.Edges.Subdir = []*Dirs{} },
			func(n *Dirs, e *Dirs) { n.Edges.Subdir = append(n.Edges.Subdir, e) }); err != nil {
			return nil, err
		}
	}
	if query := dq.withPdir; query != nil {
		if err := dq.loadPdir(ctx, query, nodes,
			func(n *Dirs) { n.Edges.Pdir = []*Dirs{} },
			func(n *Dirs, e *Dirs) { n.Edges.Pdir = append(n.Edges.Pdir, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dq *DirsQuery) loadOwner(ctx context.Context, query *UsersQuery, nodes []*Dirs, init func(*Dirs), assign func(*Dirs, *Users)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Dirs)
	for i := range nodes {
		if nodes[i].users_dirs == nil {
			continue
		}
		fk := *nodes[i].users_dirs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(users.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "users_dirs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (dq *DirsQuery) loadSaves(ctx context.Context, query *SavesQuery, nodes []*Dirs, init func(*Dirs), assign func(*Dirs, *Saves)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Dirs)
	nids := make(map[uint64]map[*Dirs]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(dirs.SavesTable)
		s.Join(joinT).On(s.C(saves.FieldID), joinT.C(dirs.SavesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(dirs.SavesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(dirs.SavesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Dirs]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Saves](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "saves" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (dq *DirsQuery) loadSubdir(ctx context.Context, query *DirsQuery, nodes []*Dirs, init func(*Dirs), assign func(*Dirs, *Dirs)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Dirs)
	nids := make(map[uint64]map[*Dirs]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(dirs.SubdirTable)
		s.Join(joinT).On(s.C(dirs.FieldID), joinT.C(dirs.SubdirPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(dirs.SubdirPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(dirs.SubdirPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Dirs]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Dirs](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "subdir" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (dq *DirsQuery) loadPdir(ctx context.Context, query *DirsQuery, nodes []*Dirs, init func(*Dirs), assign func(*Dirs, *Dirs)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Dirs)
	nids := make(map[uint64]map[*Dirs]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(dirs.PdirTable)
		s.Join(joinT).On(s.C(dirs.FieldID), joinT.C(dirs.PdirPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(dirs.PdirPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(dirs.PdirPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Dirs]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Dirs](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "pdir" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (dq *DirsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dq.querySpec()
	_spec.Node.Columns = dq.ctx.Fields
	if len(dq.ctx.Fields) > 0 {
		_spec.Unique = dq.ctx.Unique != nil && *dq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dq.driver, _spec)
}

func (dq *DirsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dirs.Table, dirs.Columns, sqlgraph.NewFieldSpec(dirs.FieldID, field.TypeUint64))
	_spec.From = dq.sql
	if unique := dq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dq.path != nil {
		_spec.Unique = true
	}
	if fields := dq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dirs.FieldID)
		for i := range fields {
			if fields[i] != dirs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dq *DirsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dq.driver.Dialect())
	t1 := builder.Table(dirs.Table)
	columns := dq.ctx.Fields
	if len(columns) == 0 {
		columns = dirs.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dq.sql != nil {
		selector = dq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dq.ctx.Unique != nil && *dq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dq.predicates {
		p(selector)
	}
	for _, p := range dq.order {
		p(selector)
	}
	if offset := dq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DirsGroupBy is the group-by builder for Dirs entities.
type DirsGroupBy struct {
	selector
	build *DirsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dgb *DirsGroupBy) Aggregate(fns ...AggregateFunc) *DirsGroupBy {
	dgb.fns = append(dgb.fns, fns...)
	return dgb
}

// Scan applies the selector query and scans the result into the given value.
func (dgb *DirsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgb.build.ctx, "GroupBy")
	if err := dgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirsQuery, *DirsGroupBy](ctx, dgb.build, dgb, dgb.build.inters, v)
}

func (dgb *DirsGroupBy) sqlScan(ctx context.Context, root *DirsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dgb.fns))
	for _, fn := range dgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dgb.flds)+len(dgb.fns))
		for _, f := range *dgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DirsSelect is the builder for selecting fields of Dirs entities.
type DirsSelect struct {
	*DirsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ds *DirsSelect) Aggregate(fns ...AggregateFunc) *DirsSelect {
	ds.fns = append(ds.fns, fns...)
	return ds
}

// Scan applies the selector query and scans the result into the given value.
func (ds *DirsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ds.ctx, "Select")
	if err := ds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DirsQuery, *DirsSelect](ctx, ds.DirsQuery, ds, ds.inters, v)
}

func (ds *DirsSelect) sqlScan(ctx context.Context, root *DirsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ds.fns))
	for _, fn := range ds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
