// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/disism/karma/ent/files"
)

// Files is the model entity for the Files schema.
type Files struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// ipfs hash
	Hash string `json:"hash,omitempty"`
	// file name
	Name string `json:"name,omitempty"`
	// file size, number of bytes in the stored file
	Size uint64 `json:"size,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FilesQuery when eager-loading is set.
	Edges        FilesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FilesEdges holds the relations/edges for other nodes in the graph.
type FilesEdges struct {
	// Saves holds the value of the saves edge.
	Saves []*Saves `json:"saves,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SavesOrErr returns the Saves value or an error if the edge
// was not loaded in eager-loading.
func (e FilesEdges) SavesOrErr() ([]*Saves, error) {
	if e.loadedTypes[0] {
		return e.Saves, nil
	}
	return nil, &NotLoadedError{edge: "saves"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Files) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case files.FieldID, files.FieldSize:
			values[i] = new(sql.NullInt64)
		case files.FieldHash, files.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Files fields.
func (f *Files) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case files.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			f.ID = uint64(value.Int64)
		case files.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				f.Hash = value.String
			}
		case files.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				f.Name = value.String
			}
		case files.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				f.Size = uint64(value.Int64)
			}
		default:
			f.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Files.
// This includes values selected through modifiers, order, etc.
func (f *Files) Value(name string) (ent.Value, error) {
	return f.selectValues.Get(name)
}

// QuerySaves queries the "saves" edge of the Files entity.
func (f *Files) QuerySaves() *SavesQuery {
	return NewFilesClient(f.config).QuerySaves(f)
}

// Update returns a builder for updating this Files.
// Note that you need to call Files.Unwrap() before calling this method if this Files
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Files) Update() *FilesUpdateOne {
	return NewFilesClient(f.config).UpdateOne(f)
}

// Unwrap unwraps the Files entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *Files) Unwrap() *Files {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Files is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Files) String() string {
	var builder strings.Builder
	builder.WriteString("Files(")
	builder.WriteString(fmt.Sprintf("id=%v, ", f.ID))
	builder.WriteString("hash=")
	builder.WriteString(f.Hash)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(f.Name)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", f.Size))
	builder.WriteByte(')')
	return builder.String()
}

// FilesSlice is a parsable slice of Files.
type FilesSlice []*Files
