// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Devices is the predicate function for devices builders.
type Devices func(*sql.Selector)

// Dirs is the predicate function for dirs builders.
type Dirs func(*sql.Selector)

// Files is the predicate function for files builders.
type Files func(*sql.Selector)

// Saves is the predicate function for saves builders.
type Saves func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
